services:
  bot:
    extends:
      file: compose.build.cpu.yml
      service: bot

  llamacpp:
    extends:
      file: compose.yml
      service: llamacpp
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    gpus: all