services:
  bot:
    extends:
      file: compose.yml
      service: bot
    image: ghcr.io/sergey21000/telegram-stt-tts-bot:main-cuda

  llamacpp:
    extends:
      file: compose.yml
      service: llamacpp
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    gpus: all