services:
  bot:
    extends:
      file: compose.base.yml
      service: bot
    image: ghcr.io/sergey21000/telegram-stt-tts-bot:main-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]