services:
  bot:
    extends:
      file: compose.yml
      service: bot
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: local/stt-tts-bot:latest

  llamacpp:
    extends:
      file: compose.yml
      service: llamacpp